import './globals.css'
import { Inter } from 'next/font/google'
import Footer from './Components/footer'
import HomeNav from './Components/HomeNav/honenav'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <HomeNav/>
      {children}
      <Footer/>
      <tab className="Tab">mhtjghcjhc</tab>
      </body>
    </html>
  )
}
